server:
  port: 9001

spring:
  application:
    name: ribbon-server #服务注册到Eureka上使用的名称

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:7001/eureka/,http://localhost:7002/eureka/
  instance:
    instance-id: ribbon-server-9001
    prefer-ip-address: true #访问路径显示IP地址
